### ISSUE TITLE
Crashed with retrofit2.HttpException

### ISSUE THREAD

**Issue by gilbarbara** [fwouts/previewjs#232] opened 2022-02-19 15:24 UTC
### Describe the bug

retrofit2.HttpException: HTTP 413 Payload Too Large
at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)

### Reproduction

Open WebStorm
Chash happens

### Preview.js version

v1.1.0

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 7.66 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/Library/Caches/fnm_multishells/7159_1645235072403/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.1 - ~/Library/Caches/fnm_multishells/7159_1645235072403/bin/npm
    Watchman: 2022.02.14.00 - /usr/local/bin/watchman
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    PhpStorm: 2021.3.2
    Sublime Text: 4126 - /usr/local/bin/subl
    VSCode: 1.64.2 - /usr/local/bin/code
    Vim: 8.2 - /usr/local/bin/vim
    WebStorm: 2021.3.2
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Browsers:
    Chrome: 98.0.4758.102
    Chrome Canary: 101.0.4897.0
    Edge: 98.0.1108.56
    Firefox: 97.0.1
    Firefox Developer Edition: 98.0
    Safari: 15.3
```

### Used Package Manager

npm

### Preview.js control-plane.log (useful for crashes)

```shell
nothing
```

**Comment by fwouts** [comment] 2022-02-19 16:16
Well that's no good. By any chance do you have any particularly large file open in your IDE?

There's also now a "Preview.js logs" bottom panel, anything interesting there ?

Thanks!

**Comment by fwouts** [comment] 2022-02-19 18:14
I've just merged a fix. It turns out the Express server I'm using had a default limit of 100kb request payloads which I wasn't aware of, so files larger than 100kb would have resulted in a crash.

A new release v1.1.1 with this fix is awaiting approval by JetBrains now.

Thanks again for reporting!

**Comment by gilbarbara** [comment] 2022-02-20 05:57
That was fast! 💨
Thanks

**Comment by fwouts** [comment] 2022-02-22 00:34
It's live now! Let me know if that fixed it.

**Comment by gilbarbara** [comment] 2022-03-10 18:39
hey @fwouts 

Sorry for the late reply.
I didn't get this error anymore but most of the time the plugin doesn't work as expected, there's no link to preview the component.
Sometimes there's a crash log with: `retrofit2.HttpException: HTTP 500 Internal Server Error` but nothing in the plugin log panel.
Do you want me to open a new issue about it?

The complete error:
Preview.js crashed
			Please report this issue at https://github.com/fwouts/previewjs/issues
			retrofit2.HttpException: HTTP 500 Internal Server Error
			at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
			at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
			at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
			at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
			at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
			at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
			at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by fwouts** [comment] 2022-03-10 23:07
Thank you for following up. It looks like I'm going to need to start using IntelliJ as my primary IDE for a while to catch these bugs before you do :)

Do you happen to have any public repo where this occurs?

**Comment by fwouts** [comment] 2022-03-15 05:40
I've now switched to IntelliJ for development and successfully reproduced it, cheers :)

**Comment by gilbarbara** [comment] 2022-03-16 03:27
hey @fwouts 

You can try this one: https://github.com/gilbarbara/react-floater

I've just opened it and there are no errors, but also no link to open the components in Preview.js

**Comment by fwouts** [comment] 2022-03-17 05:54
Thanks for the repo, it was quite helpful to nail down the issue. This should be fixed in v1.4.0 which is now pending approval by JetBrains :) Hope you like the updated design too!

**Comment by fwouts** [comment] 2022-03-17 07:58
Well it looks like one bug was fixed but there are actually more. Another release coming soon hopefully!

**Comment by fwouts** [comment] 2022-03-17 17:57
Hey @gilbarbara, v1.4.1 is now available. It should fix the bug you mentioned, and also works better with monorepos (which were previously broken). Would you be able to try it out?

**Comment by gilbarbara** [comment] 2022-03-18 11:51
@fwouts Downloading it right now!

**Comment by gilbarbara** [comment] 2022-03-18 11:56
It crashed right away.

```
Preview.js crashed

java.net.SocketTimeoutException: timeout at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:146) at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158) at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337) at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427) at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320) at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242) at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213) at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115) at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172) at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.net.SocketTimeoutException: Read timed out at java.base/java.net.SocketInputStream.socketRead0(Native Method) at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115) at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168) at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140) at okio.InputStreamSource.read(JvmOkio.kt:93) at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125) ... 24 more
```

**Comment by fwouts** [comment] 2022-03-18 12:03
That's a new one, I wonder if it's caused by the update itself. I wonder if reinstalling the plugin helps?

**Comment by fwouts** [comment] 2022-03-18 13:04
Looking into [the code](https://github.com/fwouts/previewjs/blob/2aa2afd84b25ae3f0d0f4d465920a18b281f0cc4/integrations/intellij/src/main/kotlin/com/previewjs/intellij/plugin/services/PreviewJsService.kt#L77) a bit closer, it looks like the error "Preview.js crashed" is a little too alarmist.

In fact, it's just one particular request that timed out. The rest might still work!

I'll make the error reporting more precise. Thanks again for your help.

**Comment by fwouts** [comment] 2022-03-21 07:04
Hi @gilbarbara, in case you're still patient to try one more time, there's now 1.4.2 which should have much improved error logging, and should hopefully be more stable.

**Comment by gilbarbara** [comment] 2022-03-21 12:25
hey @fwouts 

Yes, I'll definitely help! :)

**Comment by fwouts** [comment] 2022-03-26 12:59
Hey @gilbarbara, just wondering if you had a chance to try it? :)

**Comment by gilbarbara** [comment] 2022-03-26 23:33
@fwouts Yes, I'm running for a few days.
I got a different crash once but nothing to worry about, however, most of the time I don't see a link to open the component in Preview.js. No errors and no logs.

**Comment by fwouts** [comment] 2022-03-27 10:24
Thank you @gilbarbara.

A couple of extra questions:
- Do you see anything related to Preview.js in the IntelliJ logs? (Help -> Show Logs in Finder)
- Do you see anything running on port 9120? (that's the port Preview.js uses to communicate with IntelliJ)

**Comment by gilbarbara** [comment] 2022-03-28 19:52
@fwouts I'll use your suggestions to debug the next time and report back

**Comment by fwouts** [comment] 2022-03-28 21:44
Thank you! The empty logs issue should be solved in 1.4.3 which is now out, and I've got a bunch of improvements coming out in 1.5.0 in the next couple of days. I'm hopeful one of these will help...

**Comment by fwouts** [comment] 2022-04-01 10:49
Hi @gilbarbara, just another update v1.5.1 is now out with all the improvements, hopefully some progress in our debugging journey!

**Comment by gilbarbara** [comment] 2022-04-01 12:36
Hey @fwouts 
I'm running it already! Huge improvement! 👏🏻

**Comment by fwouts** [comment] 2022-04-03 07:14
Awesome, does that mean you're not seeing bugs anymore? 😅

**Comment by fwouts** [comment] 2022-04-19 01:37
Closing this as it seems fixed, feel free to reopen if that's not the case of course :)

**Closed by fwouts** 2022-04-19 01:37 UTC
Labels: bug, intellij
