### ISSUE TITLE
Automatically use the project's own vite.config.ts 

### ISSUE THREAD

**Issue by valgeirb** [fwouts/previewjs#537] opened 2022-05-03 10:59 UTC
Thanks for this great package. 

I've mostly run into problems when developing because of issues related to the plugins I'm using in my `vite.config.ts` - things like [auto importing APIs](https://github.com/antfu/unplugin-auto-import) as an example. 

This makes it so that I can't really use previewjs smoothly - is there a way to make previewjs use the project's own `vite.config.ts`?

**Comment by fwouts** [comment] 2022-05-03 11:10
Hey @valgeirb, that's a good question.

At this stage you can't directly use your `vite.config.ts` because it may conflict with Preview.js's own plugins, but you can at least add the plugins you want with:

```js
module.exports = {
  vite: {
    plugins: [ ... ]
  }
};
```

Would this help?

**Comment by fnky** [comment] 2022-12-29 09:03
The problem is that you cannot import TypeScript files (i.e. `vite.config.ts`) into the `preview.config.js` in order to easily reuse your own vite config. It would require you to transpile your Vite config from TS to JS, which is not ideal for most projects.

In our case, we have multiple projects that extends from the same base config, which also imports a TypeScript file that contains global variables definitions from various environment variables and config values, passed to the runtime.

It would be great if the Preview.js config could also be a TypeScript file, just like Vite. That way we can import other TypeScript files as needed to extend our config.

**Comment by fwouts** [comment] 2023-03-21 23:14
I'm cleaning up issues and realised I forgot to close this one. Preview.js picks up your Vite config automatically since a few months ago.

It's still not possible to use TypeScript in `preview.config.js` but it doesn't seem essential anymore. Feel free to open a separate issue if you feel that's the case!

**Closed by fwouts** 2023-03-21 23:14 UTC
Labels: enhancement, fix merged, fix shipped
