### ISSUE TITLE
command 'previewjs.open' not found

### ISSUE THREAD

**Issue by TheAussieStew** [fwouts/previewjs#948] opened 2022-08-18 05:52 UTC
### Describe the bug

When I attempt to open a component preview using Preview.js, it shows me this error

### Reproduction

1. Go to a react component
2. Preview a component using the React Preview 

### Preview.js version

v1.1.13

### Framework

React 17.0.2

### System Info

```shell
System:
    OS: macOS 11.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4850HQ CPU @ 2.30GHz
    Memory: 129.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.64.0 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.2
```

### Used Package Manager

yarn

### Extension logs (useful for crashes)

```shell
[2022-08-18 12:27:06.782] [exthost] [error] Activating extension zenclabs.previewjs failed due to an error:
[2022-08-18 12:27:06.782] [exthost] [error] TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: base64url
    at Buffer.toString (buffer.js:803:11)
    at Object.<anonymous> (/Users/conwayying/.vscode/extensions/zenclabs.previewjs-1.12.0/dist/index.js:1991:54)
    at Module.u._compile (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:1313)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.i._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:32271)
    at Function.p._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:28855)
    at Function.v._load (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:107:60382)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.r [as __$__nodeRequire] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at w._loadCommonJSModule (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:30425)
    at w._doActivateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13341)
    at w._activateExtension (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:12293)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
```

### Anything else?

Related to #635

**Comment by fwouts** [comment] 2022-08-18 11:03
Thank you for the logs!

This should be fixed in v1.12.1, which just went live in the VS Code Marketplace. You may need to uninstall and reinstall it to see the latest version.

Let me know if that fixes it!

**Closed by fwouts** 2022-08-18 11:03 UTC
Labels: bug, fix merged, vscode, fix shipped

**Comment by TheAussieStew** [comment] 2022-08-19 00:35
I'm running into this problem here:

"Preview.js needs NodeJS 14+ but running `node` failed.

Is it installed? You may need to restart your IDE."

But it actually is installed, I have version 14.18.1

**Comment by fwouts** [comment] 2022-08-19 00:39
Fascinating. Confirming restarting VS Code does not fix the issue?

**Comment by bduff9** [comment] 2022-08-29 14:05
I don't know if a new ticket is needed but I have been getting the same error for 2 weeks:
```bash
Preview.js needs NodeJS 14.18.0+ but running `node` failed.

Is it installed? You may need to restart your IDE.
```

I have restarted both VS Code as well as my computer many times over this period and every time VS code starts up it says this.  Running node -v shows this:
```bash
❯ node -v
v16.17.0
```

I do use fnm (node switcher) so maybe that is the issue?

**Comment by fwouts** [comment] 2022-08-29 21:37
Thank you @bduff9 for mentioning this! I will test with fnm and see if that can be addressed.

Would you be able to share what OS and shell you use?

**Comment by bduff9** [comment] 2022-08-29 22:05
Sure, I am on macOS 12.5.1 and I use zsh.  Let me know if I can provide any other information to help

**Comment by fwouts** [comment] 2022-09-01 23:27
@bduff9 I couldn't reproduce with fnm but I included the above change in v1.13.0 which is now live, would you be able to try again?

**Comment by bduff9** [comment] 2022-09-02 00:09
@fwouts I just tried now by restarting my computer and then opening vs code.  Same error as before.  I then quit vs code and reopened it, but received the same error again.

**Comment by fwouts** [comment] 2022-09-02 00:29
That's too bad! Would you mind also sharing the section of your `.zshrc` where you set up `fnm`?

**Comment by bduff9** [comment] 2022-09-02 12:42
Sure!  Though there's not much there in terms of setting it up, and I'm unsure if fnm has anything to do with this.  Just know I've seen other plugins in VS Code have issues when a node switcher is used, so they usually give an option to manually set the location of the node executable to prevent that, which is why I mentioned it.

My .zshrc section for fnm:
```bash
...
# Node development
eval "$(fnm env --use-on-cd)"
...
```

**Comment by TheAussieStew** [comment] 2022-09-22 10:53
Making a note that updating VSCode was what fixed it for me. Cheers @fwouts !

**Comment by fwouts** [comment] 2022-10-04 22:59
@bduff9 I've just published Preview.js v1.14 which has some improvements to how it launches Node (see https://github.com/fwouts/previewjs/pull/1044).

I believe it should work with `fnm` now!
