### ISSUE TITLE
Not working on vscode remote mode

### ISSUE THREAD

**Issue by chenyuantao** [fwouts/previewjs#642] opened 2022-06-02 03:34 UTC
### Describe the bug

Not working on vscode remote mode

### Reproduction

Not working on vscode remote mode

### Preview.js version

latest

### Framework

React 18.0.0

### System Info

```shell
linux
```

### Used Package Manager

npm

**Comment by fwouts** [comment] 2022-06-02 04:15
Duplicate of https://github.com/fwouts/previewjs/issues/66

Hoping to work on this in the next couple of months.

**Comment by fwouts** [comment] 2022-06-02 11:36
Duplicate of #66

**Closed** 2022-06-02 11:36 UTC
Labels: pending triage, vscode
