### ISSUE TITLE
The Preview.js client encountered a fatal error. This is most likely due to a bug in Preview.js itself and not in your code.

### ISSUE THREAD

**Issue by baditaflorin** [fwouts/previewjs#1434] opened 2023-03-10 13:29 UTC
### Describe the bug

The Preview.js client encountered a fatal error. This is most likely due to a bug in Preview.js itself and not in your code.

Please report the following in the [GitHub repo](https://github.com/fwouts/previewjs/issues):
```
Type alias name cannot be 'default'. (907:6)
  905 |             }
  906 |
> 907 | type default<T,> = {
      |      ^
  908 |               ["maxSize"]: number
  909 | ["insert"]: (...params: any[]) => (default<T>)
  910 | ["get"]: (...params: any[]) => (T | undefined)
SyntaxError: Type alias name cannot be 'default'. (907:6)
  905 |             }
  906 |
> 907 | type default<T,> = {
      |      ^
  908 |               ["maxSize"]: number
  909 | ["insert"]: (...params: any[]) => (default<T>)
  910 | ["get"]: (...params: any[]) => (T | undefined)
    at Fn (http://localhost:3140/assets/index-b3bf10d1.js:1196:25040)
    at Wd (http://localhost:3140/assets/index-b3bf10d1.js:1452:10991)
    at Object.fp [as parse] (http://localhost:3140/assets/index-b3bf10d1.js:1452:11316)
    at Object.Mr [as parse] (http://localhost:3140/assets/index-b3bf10d1.js:1120:1412)
    at On (http://localhost:3140/assets/index-b3bf10d1.js:1121:16386)
    at Ta (http://localhost:3140/assets/index-b3bf10d1.js:1125:643)
    at http://localhost:3140/assets/index-b3bf10d1.js:1196:7616
    at Object.format (http://localhost:3140/assets/index-b3bf10d1.js:1196:7708)
    at Sge (http://localhost:3140/assets/index-b3bf10d1.js:1454:82)
    at ysr (http://localhost:3140/assets/index-b3bf10d1.js:1538:3)
```

### Reproduction

Trying to preview a function

### Preview.js version

v1.19.3

### Framework

React 18

### System Info

```shell
mac os with M1
```

### Used Package Manager

npm

### Extension logs (useful for crashes)

```shell
Starting Preview.js daemon...
Streaming daemon logs to: /Users/florin/.vscode/extensions/zenclabs.previewjs-1.19.3/dist/daemon.log
[install:begin] Running pnpm install...
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +364
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/florin/Library/pnpm/store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 364, reused 163, downloaded 1, added 160
Progress: resolved 364, reused 306, downloaded 3, added 298
Progress: resolved 364, reused 360, downloaded 3, added 362
Progress: resolved 364, reused 360, downloaded 3, added 363

dependencies:
+ @previewjs/core 18.0.1
+ @previewjs/plugin-preact 3.1.0
+ @previewjs/plugin-react 9.1.0
+ @previewjs/plugin-solid 6.1.0
+ @previewjs/plugin-svelte 4.0.0
+ @previewjs/plugin-vue2 8.0.0
+ @previewjs/plugin-vue3 8.0.0
+ @previewjs/pro 1.10.2
+ @previewjs/vfs 2.0.0

Done in 5.1s
Progress: resolved 364, reused 360, downloaded 4, added 364, done
[install:end] Done.
[ready] Preview.js daemon server is now running at http://localhost:9315
No compatible Preview.js plugin for workspace: /Users/florin/Documents/GITHUB_PROJECTS/mapbond
Creating Preview.js workspace (plugin: @previewjs/plugin-react) at /Users/florin/Documents/GITHUB_PROJECTS/mapbond/frontend
✨ Created Preview.js workspace for: /Users/florin/Documents/GITHUB_PROJECTS/mapbond/frontend
Warning: encountered some TypeScript error(s) while resolving types.
This may be safe to ignore, but could help point out why some components are not detected by Preview.js.
src/App.tsx:
Cannot find module './App.module.css' or its corresponding type declarations.
src/Components/AccordionItem/AccordionItem.tsx:
[...]
Around 80 Cannot find module errors here that I have not included 
[...] 

Preview.js Server running at http://localhost:3140.
Preview.js Server stopped.
```

**Comment by fwouts** [comment] 2023-03-10 22:46
Duplicate of #1435.

**Closed by fwouts** 2023-03-10 22:46 UTC
Labels: bug, vscode
