### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by edemaine** [fwouts/previewjs#482] opened 2022-04-18 17:01 UTC
**Is your feature request related to a problem? Please describe.**
I write my components (React and SolidJS) in CoffeeScript.

**Describe the solution you'd like**
Ideally CoffeeScript files would be supported, with components detected in the same way as JavaScript.

**Describe alternatives you've considered**
I notice PR #277 explicitly mentions that CoffeeScript is not supported, and disabled accidentally triggering, which is a good first step. But it doesn't help me use PreviewJS.

**Additional context**
CoffeeScript 2 added roughly Babel-compatible parse tree generation roughly a year ago, enabling eslint and Prettier to run directly on CoffeeScript code (with appropriate plugins). So maybe it's not difficult to add now?

**Comment by fwouts** [comment] 2022-04-18 18:56
Hi @edemaine, thanks for filing this.

The problem is that Preview.js relies heavily on the TypeScript parser for detection of components. Combining this with the Coffeescript parser may technically be possible (Preview.js abstracts away the file system and supports transparently transforming files), but it would likely be a bit slow with this double parsing step.

Out of curiosity, do you type your components' props when using Coffeescript? I'm asking because even if it were supported, you may not get a great experience in Preview.js if it's not able to auto-generate props for your components based on their type.

At this stage I'm inclined not to implement this because of the future maintenance cost. However if it becomes obvious that a significant number of users need this and that Coffeescript is becoming mainstream again, I'd of course reconsider!

Anyone wanting this, please thumb up the original post and/or reply with your particular circumstances.

**Comment by edemaine** [comment] 2022-04-18 20:14
Ah, sorry, I hadn't realized that autovivifying props based on types was part of PreviewJS. That's cool! But I agree that this makes it much harder to apply to CoffeeScript.

CoffeeScript *does* support JSDoc typing, and I know a few people who do it, but I haven't gotten into it yet. I've been working on a PR for CoffeeScript that would enable more first-class TypeScript typing, but it's still a ways off.  We could revisit at that point.

**Comment by fwouts** [comment] 2022-04-18 22:05
That sounds really cool! Do let me know when you have that in 👌

**Comment by fwouts** [comment] 2022-04-19 03:39
Closing this issue as there are no plans to progress forward at this stage—feel free to reopen in the future.

**Closed by fwouts** 2022-04-19 03:39 UTC
Labels: enhancement
